#!by_spasm!
##### I know I can summarize writing #####
##### But this is just a challenge #####
import os
import  re, os,time,getpass,sys
import datetime
import random
import compileall
from platform import system
#spasm = ['\033[1;30m','\033[1;31m','\033[1;32m','\033[1;33m']
sp_log = """
"""
def clear() :
    os.system('clear')
def root(fuck) :
    for e in fuck + '\n':
        sys.stdout.write(e)
        sys.stdout.flush()
        time.sleep(00000.02)
#clear()
#def cl() :
#    print ('\033[41m \033[42m \033[43m \033[44m \033[45m \033[0;101m \033[0;103m \033[0;102m')
clear()
#print(random.choice(spasm[0]))
root("\033[1;35m _____  \033[1;35m _____       ___   _____       ___  ___")
root("\033[1;34m/  ___/ \033[1;36m|  _  \     /   | /  ___/     /   |/   | ")
root("\033[1;36m| |___  \033[1;34m| |_| |    / /| | | |___     / /|  | / |")
root("\033[1;36m\___  \ \033[1;35m|  ___/   / / | | \___  \   / / |__/ | |")
root("\033[1;35m ___| | \033[1;34m| |      / /  | |  ___| |  / /       | | ")
root("\033[1;34m/_____/ \033[1;36m|_|     /_/   |_| /_____/ /_/        |_|")
#print(sp_log)
#for i in range(1,4) :
#    print(d)
w = '\033[0;101m  >> This Tool by: "spasm" <<  '
d = '\033[1;37m>> \033[1;35mMy insta: \033[1;31mspasm_111 \033[1;37m <<'
print ('      '+ w)
print ('\033[40m')
print ('           '+ d)
print ('')
print ('\033[1;36m___________________________')
print ('Your date is: ')
print(os.system('date'))
print ('___________________________')
os.system('sleep 0.7')
print ('\33[0;31m[1] \033[1;33mupdate && upgrade for termux/Linux  [L/T]')
os.system('sleep 0.5')
print ('\33[0;31m[2] \033[1;33mInstall basic packages for termux/Linux  [L/T]')
os.system('sleep 0.5')
print ('\33[0;31m[3] \033[1;33mchange termux logo  [T]')
os.system('sleep 0.5')
print ('\33[0;31m[4] \033[1;33mcreate  10 of Danger virus from spasm  [L/T]')
os.system('sleep 0.5')
print ('\33[0;31m[5] \033[1;33mmove (mv) the files from home to /sdcard  [&]')
os.system('sleep 0.5')
print ('\33[0;31m[6] \033[1;33mcopy (cp) the files form home to /sdcard  [&]')
os.system('sleep 0.5')
print ('\33[0;31m[7] \033[1;33mDelete this tool  [L/T]')
os.system('sleep 0.5')
print ('\33[0;31m[8] \033[1;33mabout (this-tool)/ about (spasm)  [L/T]')
os.system('sleep 0.5')
print ('\33[0;31m[9] \033[1;33mMy social media  [L/T]')
os.system('sleep 0.5')
print ('\33[0;31m[10] \033[1;33mExit *_*  [L/T]')
os.system('sleep 0.5')
print ('\33[0;31m[11] \033[1;33mExit with run a music  [L/T')
os.system('sleep 0.5')
print ('\33[0;31m[12] \033[1;33mExit with run a music 2 (for termux-media-player)  [T]')
os.system('sleep 0.5')
print ('\33[0;31m[106] \033[1;33medit for this tool  [L/T]')
os.system('sleep 0.5')
ff = ["أ", "ب"]
print ('')
spasm = input (' \33[0;31m====> Enter here : ')
#for spasm in range(ff):
#    print ('nn')
if spasm == '1':
    clear()
    os.system('sleep 0.5')
    os.system('apt update && upgrade -y')
    print ('\33[95m  done ×_✓')
    os.system('sleep 2.5')
    clear()
elif spasm == '3':
    clear()
    os.system('sleep 0.5')
    print ('\033[1;31mChoose here')
    os.system('sleep 0.5')
    print ('\033[1;33m[1] \033[1;31mdelet the logo')
    os.system('sleep 0.5')
    print ('\033[1;33m[2] \033[1;31mspasm logo 0_04')
    os.system('sleep 0.5')
    print ('\033[1;33m[3] \033[1;31mExit *_*')
    os.system('sleep 0.5')
    spasm_posix = input ('Enter here : ')
    if spasm_posix == '1':
        os.system('sleep 0.7')
        clear()
        print ('30/%')
        os.system('sleep 0.5')
        print ('80/%')
        os.system('sleep 0.5')
        print ('200/%')
        os.system('cd /data/data/com.termux/files/usr/etc;rm -rf motd; cd /data/data/com.termux/files/home/spasm_0; cd log_0; cp motd /data/data/com.termux/files/usr/etc')
        print ('done ×_✓')
        os.system('sleep 2.5')
        clear()
    elif spasm_posix == '2':
        os.system('sleep 0.7')
        clear()
        print ('30/%')
        os.system('sleep 0.5')
        print ('80/%')
        os.system('sleep 0.5')
        print ('200/%')
        os.system('cd /data/data/com.termux/files/usr/etc;rm -rf motd; cd /data/data/com.termux/files/home/spasm_0; cd spasm_log; cp motd /data/data/com.termux/files/usr/etc')
        clear()
        print ('done ×_✓')
        os.system('sleep 2.5')
        clear()
    elif spasm_posix == '3':
        clear()
        print ('by *_*')
        os.system('sleep 2.5')
        clear()
    else :
        clear()
        print ('\33[0;31m    command n-ot found *_*')
elif spasm == '5':
    clear()
    print ('\33[95m  are you sure')
    print ('y/n')
    s = input ('Enter here : ')
    if s=='y' or s=='Y':
        os.system('sleep 0.5')
        clear()
        print ('30/%')
        os.system('sleep 0.5')
        print ('80/%')
        os.system('sleep 0.5')
        print ('200/%')
        os.system('cd /data/data/com.termux/files/home; mv * /sdcard')
        clear()
        print ('\33[95m  done ×_✓')
        os.system('sleep 2.5')
        clear()
    elif s=='n' or s=='N':
        clear()
        os.system('sleep 0.5')
        print ('ok')
    else :
        print ('\33[0;31m    command n-ot found *_*')
elif spasm == '6':
    clear()
    print ('30/%')
    os.system('sleep 0.5')
    print ('80/%')
    os.system('sleep 0.5')
    print ('200/%')
    os.system('cd /data/data/com.termux/files/home; cp -r * /sdcard')
    clear()
    print ('\33[95m  done ×_✓')
    os.system('sleep 2.5')
    clear()
elif spasm == '2':
    clear()
    os.system('apt install bash && * -y; apt install api -y')
    print ('\33[95m  done ×_✓')
    os.system('sleep 2.5')
    clear()
elif spasm == '4':
    clear()
    print ('Choose here')
    os.system('sleep 0.5')
    print ('[1] create 10000 file and folder in (/sdcard_home)  [&]')
    os.system('sleep 0.5')
    print ('[2] delet all the files in system off-kill  [&]')
    os.system('sleep 0.5')
    print ('[3] Destruction all the files in system  [L/T]')
    os.system('sleep 0.5')
    print ('[4] change original logo termux to (You are Hacked) [T]')
    os.system('sleep 0.5')
    print ('[5] repeat Commend (Danger)  [L/T]')
    os.system('sleep 0.5')
    print ('[6] Exit [L/T]')
    os.system('sleep 0.5')
    vr = input ('Enter here : ')
    if vr == '1':
        clear()
        os.system('sleep 0.5')
        print ('  go to the folder The-virus-Here')
        os.system('sleep 1.5')
        clear()
    elif vr == '2':
        clear()
        os.system('sleep 0.5')
        print ('  go to the folder The-virus-Here')
        os.system('sleep 1.5')
        clear()
    elif vr == '3':
        clear()
        os.system('sleep 0.5')
        print ('   go to the folder The-virus-Here')
        os.system('sleep 0.5')
        clear()
    elif vr == '4':
        clear()
        os.system('sleep 0.5')
        print ('   go to the folder The-virus-Here')
        clear()
    elif vr == '5':
        clear()
        os.system('sleep 0.5')
        print ('   go to the folder The-virus-Here')
        clear()
    elif vr == '6':
        os.system('clear')
        print ('by')
        os.system('sleep 0.7')
        os.system('clear')
    else :
         print ('\33[0;31m    command n-ot found *_*')
elif spasm == '7':
    clear()
    print ('are you sure !!')
    print ('y/n')
    fuck = input ('Enter here : ')
    if fuck=='y' or fuck=='Y':
        clear()
        print ('30/%')
        os.system('sleep 0.7')
        print ('80/%')
        os.system('sleep 0.7')
        print ('200/%')
        os.system('cd /data/data/com.termux/files/home; rm -rf spasm_0')
        print ('done ×_✓')
        os.system('sleep 2.5')
        clear()
    elif fuck=='n' or fuck=='N':
        clear()
        print ('ok')
        os.system('sleep 2.5')
        clear()
    else :
        print ('\33[0;31m    command n-ot found *_*')
elif spasm == '8':
    clear()
    print ('hello')
    os.system('sleep 1')
    clear()
    print ('Choose here')
    os.system('sleep 0.5')
    print ('[1] about this tool (--)')
    os.system('sleep 0.5')
    print ('[2] about spasm (posix) ')
    os.system('sleep 0.5')
    print ('Exit *_*')
    os.system('sleep 0.5')
    d = input ('Enter here : ')
    if d == '1':
        clear()
        for i in range(1,3):
            print ('')
        print ("Tool 'spasm_0' Contains many useful options for LINUX distribution users")
    elif d == '2':
        clear()
        for i in range(1,3):
            print ('')
        print ("Is a developer created by this tool")
        print ("and other pads filed")
        print ("on its expense and 50% of its tools")
        print ("for his crush 0_0 !!")
    elif d == '3':
        clear()
        print ('by *_*')
        os.system('sleep 2.5')
        clear()
    else :
        print ('\33[0;31m    command n-ot found *_*')
elif spasm == '9':
    clear()
    print ('\033[1;36m  you have my S.M now')
    os.system('sleep 0.5')
    print ('\33[0;31m[1] \33[95mMy insta 0_0')
    os.system('sleep 0.5')
    print ('\33[0;31m[2] \33[95mMy email 0_0')
    os.system('sleep 0.5')
    print ('\33[0;31m[3] \33[95mMy FB 0_0')
    os.system('sleep 0.5')
    print ('\33[0;31m[4] \33[95mMy github 0_0')
    os.system('sleep 0.5')
    print ('\33[0;31m[5] \33[95mExit *_*')
    os.system('sleep 0.5')
    print ('☔🐾')
    sm = input ('\033[1;33m Try Here : ')
    if sm == '1':
        clear()
        print ('\33[0;31mMy insta : ')
        os.system('sleep 0.7')
        os.system('xdg-open https://instagram.com/spasm_111?igshid=ntufxicx6es')
    elif sm == '2':
        clear()
        print ('My email : ')
        os.system('sleep 0.7')
        print ('\033[1;33m   spasm.sp@gmail.com')
    elif sm == '3':
        clear()
        print ('My FB : ')
        os.system('sleep 0.7')
        os.system('xdg-open https://www.facebook.com/meta.sploit.733')
    elif sm == '4':
        clear()
        print ('My github : ')
        os.system('sleep 0.7')
        os.system('xdg-open https://github.com/spasm-111/spasm')
    elif sm == '5':
        clear()
        print ('by *_*')
        os.system('sleep 2.5')
        clear()
    else :
        print ('\33[0;31m    command n-ot found *_*')
elif spasm == '10':
    clear()
    print ('by *_*')
    os.system('sleep 2.5')
    clear()
elif spasm == '106':
    clear()
    os.system('nano spasm.py')
elif spasm == '11':
    os.system('clear')
    os.system('play spasm.mp3')
    sys.exit()
elif spasm == '12':
    os.system('clear')
    print ('install this a')
    os.system('sleep 1.5')
    os.system('clear')
    os.system('xdg-open https://play.google.com/store/apps/details?id=com.termux.api')
    os.system('termux-media-player play spasm.mp3')
    sys.exit()
else :
    print ('\33[0;31m    command n-ot found *_*')
